### ISSUE TITLE
Problem while trying to set up Linenoise

### ISSUE THREAD

**Issue by probonopd** [samcv/rakudo-appimage-module-test-automation#1]
Running on `xubuntu-16.04-desktop-amd64.iso` I get:

```
me@host:~$ /home/me/Downloads/org.perl6.rakudo-x86_64.AppImage
I ran into a problem while trying to set up Linenoise: Could not open /tmp/.mount_p4BbXV/usr/(Linenoise). Failed to stat file: no such file or directory

Continuing without tab completions or line editor
You may want to consider using rlwrap for simple line editor functionality

To exit type 'exit' or '^D'
```

Unfortunately I don't know enough about Perl to be of any help here.

**Comment by samcv** [comment]
There is an issue with the most recent AppImage, I'm trying to look at a previous working AppImage and will try and fix this.

**Comment by samcv** [comment]
Can you try RC2? Seems my wrapper script to resolve full paths from relative paths was breaking things. Putting that fancyness away until I get tests passing to ensure no breakage.
https://github.com/samcv/rakudo-appimage/releases/tag/2017.01-AI-RC2

**Comment by probonopd** [comment]
Looks good, at least the error doesn't appear anymore:

```
me@host:~$ /home/me/Downloads/org.perl6.rakudo-x86_64\(1\).AppImage 
To exit type 'exit' or '^D'
> help
===SORRY!=== Error while compiling:
Undeclared routine:
    help used at line 1

> exit
```
